<?php

/**
 * @file
 * Hook implementations.
 */

declare(strict_types = 1);

/**
 * Implements hook_theme().
 *
 * @return mixed[]
 */
function shoutbox_theme(): array {
  $themes = [];
  $themes['shoutbox'] = [
    'render element' => 'elements',
    'file' => 'shoutbox.page.inc',
    'template' => 'shoutbox',
  ];
  $themes['shout'] = [
    'render element' => 'elements',
    'file' => 'shout.page.inc',
    'template' => 'shout',
  ];

  return $themes;
}
